//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudcalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personeller
    {
        public int personelid { get; set; }
        public string personelad { get; set; }
        public string personelsoyad { get; set; }
        public string personelyas { get; set; }
        public Nullable<System.DateTime> personeldogumtarihi { get; set; }
    }
}
